### ISSUE TITLE
README

### ISSUE THREAD

**Issue by pelikhan** [alankrantas/pxt-ESP8266_ThingSpeak#2]
- use ```blocks to render blocks
- don't use screenshot images

**Comment by alankrantas** [comment]
Fixed.

I prefer to keep screenshots for people who searched this extension via google or github (I does this a lot, and I know other people do too). The pic will give them an quick idea what's the extension actually like without having to download them first in MakeCode.

**Comment by pelikhan** [comment]
Good point.

**Comment by pelikhan** [comment]
Link to https://makecode.microbit.org/pkg/alankrantas/pxt-ESP8266_ThingSpeak
